In [1]:
import pandas as pd
df = pd.read_csv(r"D:\Downloads\insurance_data.csv")

In [2]:
df.head()

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[["age", "affordibility"]], df.bought_insurance, test_size=0.25)

In [6]:
len(X_train)

21

In [7]:
len(X_test)

7

**This is used for the scaling...**

In [8]:
X_train = X_train.copy()
X_train["age"] = X_train["age"]/100

X_test = X_test.copy()
X_test["age"] = X_test["age"]/100

In [9]:
X_train

     age  affordibility
10  0.18              1
18  0.19              0
20  0.21              1
0   0.22              1
5   0.56              1
13  0.29              0
3   0.52              0
17  0.58              1
12  0.27              0
4   0.46              1
24  0.50              1
7   0.60              0
16  0.25              0
27  0.46              1
9   0.61              1
8   0.62              1
21  0.26              0
26  0.23              1
19  0.18              1
6   0.55              0
22  0.40              1

In [14]:
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation="sigmoid")
])

model.compile(optimizer="adam",
              loss="binary_crossentropy",
              metrics=["accuracy"])

model.fit(X_train, y_train, epochs=5000)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5714 - loss: 0.8272
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5714 - loss: 0.8268
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step - accuracy: 0.5714 - loss: 0.8264
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.5714 - loss: 0.8260
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - accuracy: 0.5714 - loss: 0.8256
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step - accuracy: 0.5714 - loss: 0.8253
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step - accuracy: 0.5714 - loss: 0.8249
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5714 - loss: 0.8245
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5714 - loss: 0.8241
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.5714 - loss: 0.8237
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accuracy: 0.5714 - loss: 0.8234
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5714 - loss: 0.8230
Epoch 13/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5714 - loss: 0.8226
Epoch 14/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5714 - loss: 0.8222
Epoch 15/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.5714 - loss: 0.8219
Epoch 16/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.5714 - loss: 0.8215
Epoch 17/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step - accuracy: 0.5714 - loss: 0.8211
Epoch 18/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 0.5714 - loss: 0.8207
Epoch 19/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 451ms/step - accuracy: 0.5714 - loss: 0.8204
Epoch 20/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - accuracy: 0.5714 - loss: 0.8200
Epoch 21/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.5714 - loss: 0.8196
Epoch 22/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step - accuracy: 0.5714 - loss: 0.8193
Epoch 23/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - accuracy: 0.5714 - loss: 0.8189
Epoch 24/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5714 - loss: 0.8185
Epoch 25/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5714 - loss: 0.8182
Epoch 26/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5714 - loss: 0.8178
Epoch 27/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5714 - loss: 0.8174
Epoch 28/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.5714 - loss: 0.8171
Epoch 29/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.5714 - loss: 0.8167
Epoch 30/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 284ms/step - accuracy: 0.5714 - loss: 0.8163
Epoch 31/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 0.5714 - loss: 0.8160
Epoch 32/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - accuracy: 0.5714 - loss: 0.8156
Epoch 33/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 0.5714 - loss: 0.8153
Epoch 34/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5714 - loss: 0.8149
Epoch 35/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.5714 - loss: 0.8146
Epoch 36/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5714 - loss: 0.8142
Epoch 37/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 192ms/step - accuracy: 0.5714 - loss: 0.8139
Epoch 38/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - accuracy: 0.5714 - loss: 0.8135
Epoch 39/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5714 - loss: 0.8132
Epoch 40/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5714 - loss: 0.8128
Epoch 41/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5714 - loss: 0.8125
Epoch 42/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - accuracy: 0.5714 - loss: 0.8121
Epoch 43/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - accuracy: 0.5714 - loss: 0.8118
Epoch 44/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5714 - loss: 0.8114
Epoch 45/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5714 - loss: 0.8111
Epoch 46/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step - accuracy: 0.5714 - loss: 0.8108
Epoch 47/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5714 - loss: 0.8104
Epoch 48/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5714 - loss: 0.8101
Epoch 49/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.5714 - loss: 0.8097
Epoch 50/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.5714 - loss: 0.8094
Epoch 51/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.5714 - loss: 0.8091
Epoch 52/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5714 - loss: 0.8087
Epoch 53/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5714 - loss: 0.8084
Epoch 54/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5714 - loss: 0.8081
Epoch 55/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5714 - loss: 0.8077
Epoch 56/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5714 - loss: 0.8074
Epoch 57/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 0.5714 - loss: 0.8071
Epoch 58/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5714 - loss: 0.8068
Epoch 59/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5714 - loss: 0.8064
Epoch 60/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5714 - loss: 0.8061
Epoch 61/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5714 - loss: 0.8058
Epoch 62/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5714 - loss: 0.8055
Epoch 63/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5714 - loss: 0.8052
Epoch 64/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5714 - loss: 0.8048
Epoch 65/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5714 - loss: 0.8045
Epoch 66/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 241ms/step - accuracy: 0.5714 - loss: 0.8042
Epoch 67/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5714 - loss: 0.8039
Epoch 68/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5714 - loss: 0.8036
Epoch 69/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 0.5714 - loss: 0.8033
Epoch 70/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5714 - loss: 0.8029
Epoch 71/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.5714 - loss: 0.8026
Epoch 72/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5714 - loss: 0.8023
Epoch 73/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5714 - loss: 0.8020
Epoch 74/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5714 - loss: 0.8017
Epoch 75/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5714 - loss: 0.8014
Epoch 76/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5714 - loss: 0.8011
Epoch 77/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5714 - loss: 0.8008
Epoch 78/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5714 - loss: 0.8005
Epoch 79/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5714 - loss: 0.8002
Epoch 80/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5714 - loss: 0.7999
Epoch 81/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5714 - loss: 0.7996
Epoch 82/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5714 - loss: 0.7993
Epoch 83/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.5714 - loss: 0.7990
Epoch 84/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5714 - loss: 0.7987
Epoch 85/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5714 - loss: 0.7984
Epoch 86/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5714 - loss: 0.7981
Epoch 87/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step - accuracy: 0.5238 - loss: 0.7978
Epoch 88/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.5238 - loss: 0.7975
Epoch 89/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.5238 - loss: 0.7972
Epoch 90/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5238 - loss: 0.7969
Epoch 91/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5238 - loss: 0.7966
Epoch 92/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.5238 - loss: 0.7964
Epoch 93/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - accuracy: 0.5238 - loss: 0.7961
Epoch 94/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5238 - loss: 0.7958
Epoch 95/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5238 - loss: 0.7955
Epoch 96/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5238 - loss: 0.7952
Epoch 97/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.5238 - loss: 0.7949
Epoch 98/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5238 - loss: 0.7947
Epoch 99/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5238 - loss: 0.7944
Epoch 100/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 411ms/step - accuracy: 0.5238 - loss: 0.7941
Epoch 101/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.5238 - loss: 0.7938
Epoch 102/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.5238 - loss: 0.7935
Epoch 103/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.5238 - loss: 0.7933
Epoch 104/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.5238 - loss: 0.7930
Epoch 105/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - accuracy: 0.5238 - loss: 0.7927
Epoch 106/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.5238 - loss: 0.7925
Epoch 107/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - accuracy: 0.5238 - loss: 0.7922
Epoch 108/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - accuracy: 0.5238 - loss: 0.7919
Epoch 109/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.5238 - loss: 0.7916
Epoch 110/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - accuracy: 0.5238 - loss: 0.7914
Epoch 111/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5714 - loss: 0.7911
Epoch 112/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5714 - loss: 0.7908
Epoch 113/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 0.5714 - loss: 0.7906
Epoch 114/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.5714 - loss: 0.7903
Epoch 115/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5238 - loss: 0.7900
Epoch 116/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5238 - loss: 0.7898
Epoch 117/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.5238 - loss: 0.7895
Epoch 118/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5238 - loss: 0.7893
Epoch 119/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.4762 - loss: 0.7890
Epoch 120/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.4762 - loss: 0.7887
Epoch 121/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.4762 - loss: 0.7885
Epoch 122/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - accuracy: 0.4762 - loss: 0.7882
Epoch 123/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.4762 - loss: 0.7880
Epoch 124/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - accuracy: 0.4762 - loss: 0.7877
Epoch 125/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.4762 - loss: 0.7875
Epoch 126/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.4286 - loss: 0.7872
Epoch 127/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.4286 - loss: 0.7870
Epoch 128/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.4286 - loss: 0.7867
Epoch 129/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step - accuracy: 0.4286 - loss: 0.7865
Epoch 130/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - accuracy: 0.4286 - loss: 0.7862
Epoch 131/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - accuracy: 0.4286 - loss: 0.7860
Epoch 132/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.4286 - loss: 0.7857
Epoch 133/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step - accuracy: 0.4286 - loss: 0.7855
Epoch 134/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - accuracy: 0.4286 - loss: 0.7852
Epoch 135/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 241ms/step - accuracy: 0.4286 - loss: 0.7850
Epoch 136/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.4286 - loss: 0.7848
Epoch 137/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.4286 - loss: 0.7845
Epoch 138/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.4286 - loss: 0.7843
Epoch 139/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - accuracy: 0.4286 - loss: 0.7840
Epoch 140/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.4286 - loss: 0.7838
Epoch 141/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.4286 - loss: 0.7836
Epoch 142/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 0.4286 - loss: 0.7833
Epoch 143/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 212ms/step - accuracy: 0.4286 - loss: 0.7831
Epoch 144/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.4286 - loss: 0.7829
Epoch 145/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.4286 - loss: 0.7826
Epoch 146/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.4286 - loss: 0.7824
Epoch 147/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.4286 - loss: 0.7822
Epoch 148/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.4286 - loss: 0.7819
Epoch 149/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step - accuracy: 0.4286 - loss: 0.7817
Epoch 150/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.4286 - loss: 0.7815
Epoch 151/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 0.4286 - loss: 0.7812
Epoch 152/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.4286 - loss: 0.7810
Epoch 153/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.4286 - loss: 0.7808
Epoch 154/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.4286 - loss: 0.7806
Epoch 155/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.4286 - loss: 0.7803
Epoch 156/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.4286 - loss: 0.7801
Epoch 157/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - accuracy: 0.4286 - loss: 0.7799
Epoch 158/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 254ms/step - accuracy: 0.4286 - loss: 0.7797
Epoch 159/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.4286 - loss: 0.7795
Epoch 160/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.4286 - loss: 0.7792
Epoch 161/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - accuracy: 0.4286 - loss: 0.7790
Epoch 162/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.4286 - loss: 0.7788
Epoch 163/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.4286 - loss: 0.7786
Epoch 164/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 0.4286 - loss: 0.7784
Epoch 165/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 0.4286 - loss: 0.7782
Epoch 166/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - accuracy: 0.4286 - loss: 0.7779
Epoch 167/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 197ms/step - accuracy: 0.4286 - loss: 0.7777
Epoch 168/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.4286 - loss: 0.7775
Epoch 169/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.4286 - loss: 0.7773
Epoch 170/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - accuracy: 0.4286 - loss: 0.7771
Epoch 171/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.4286 - loss: 0.7769
Epoch 172/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.4286 - loss: 0.7767
Epoch 173/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.4286 - loss: 0.7765
Epoch 174/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4286 - loss: 0.7763
Epoch 175/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.4286 - loss: 0.7760
Epoch 176/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.4286 - loss: 0.7758
Epoch 177/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.4286 - loss: 0.7756
Epoch 178/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.4286 - loss: 0.7754
Epoch 179/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 0.4286 - loss: 0.7752
Epoch 180/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.4286 - loss: 0.7750
Epoch 181/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 0.4286 - loss: 0.7748
Epoch 182/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.4286 - loss: 0.7746
Epoch 183/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.4286 - loss: 0.7744
Epoch 184/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.4286 - loss: 0.7742
Epoch 185/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.4286 - loss: 0.7740
Epoch 186/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.4286 - loss: 0.7738
Epoch 187/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.4286 - loss: 0.7736
Epoch 188/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.4286 - loss: 0.7734
Epoch 189/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.4286 - loss: 0.7732
Epoch 190/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.4286 - loss: 0.7730
Epoch 191/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.4286 - loss: 0.7728
Epoch 192/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.4286 - loss: 0.7727
Epoch 193/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.4286 - loss: 0.7725
Epoch 194/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.4286 - loss: 0.7723
Epoch 195/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.4286 - loss: 0.7721
Epoch 196/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.4286 - loss: 0.7719
Epoch 197/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.4286 - loss: 0.7717
Epoch 198/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 235ms/step - accuracy: 0.4286 - loss: 0.7715
Epoch 199/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.4286 - loss: 0.7713
Epoch 200/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.4286 - loss: 0.7711
Epoch 201/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.4286 - loss: 0.7710
Epoch 202/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.4286 - loss: 0.7708
Epoch 203/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.4286 - loss: 0.7706
Epoch 204/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.4286 - loss: 0.7704
Epoch 205/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4286 - loss: 0.7702
Epoch 206/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.4286 - loss: 0.7700
Epoch 207/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.4286 - loss: 0.7698
Epoch 208/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.4286 - loss: 0.7697
Epoch 209/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.3810 - loss: 0.7695
Epoch 210/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.3810 - loss: 0.7693
Epoch 211/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.3810 - loss: 0.7691
Epoch 212/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.3810 - loss: 0.7689
Epoch 213/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.3810 - loss: 0.7688
Epoch 214/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.3810 - loss: 0.7686
Epoch 215/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.3810 - loss: 0.7684
Epoch 216/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.3810 - loss: 0.7682
Epoch 217/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.3810 - loss: 0.7681
Epoch 218/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.3810 - loss: 0.7679
Epoch 219/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.3333 - loss: 0.7677
Epoch 220/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.3333 - loss: 0.7675
Epoch 221/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.3333 - loss: 0.7674
Epoch 222/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.3333 - loss: 0.7672
Epoch 223/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.3333 - loss: 0.7670
Epoch 224/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.3333 - loss: 0.7669
Epoch 225/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.3333 - loss: 0.7667
Epoch 226/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.3333 - loss: 0.7665
Epoch 227/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.3333 - loss: 0.7663
Epoch 228/5000

In [15]:
model.evaluate(X_test, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 275ms/step - accuracy: 1.0000 - loss: 0.4378

[0.43776533007621765, 1.0]

In [ ]:
coef, intercept = model.get_weights()
coef, intercept

#This gives the w1 and w2 also the bias
#for the neural network

(array([[3.7773602],
        [1.1495365]], dtype=float32),
 array([-2.5030148], dtype=float32))

**Building the neural network with python only**

In [29]:
import numpy as np
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [30]:
sigmoid(21)

np.float64(0.9999999992417439)

In [31]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

In [34]:
prediction_function(.18, 1)

array([0.33770162], dtype=float32)

**Writing the gradient descent function from the scratch**

In [35]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1-epsilon) for i in y_predicted]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

_From the gradient descent we can find out the desired weights for our neural network which gives best prediction and minimal loss_

In [39]:
def gradient_descent(age, affordibility, y_true, epochs, loss_threshold):
    w2=w1=1
    bias = 0
    rate = 0.5
    n = len(age)

    for i in range(epochs):
        weighted_sum = w1*age + w2*affordibility + bias
        y_predicted = sigmoid(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1_derivative = (1/n)*(np.dot(np.transpose(age), (y_predicted-y_true)))
        w2_derivative = (1/n)*(np.dot(np.transpose(affordibility), (y_predicted-y_true)))
        bias_derivative = (1/n)*np.sum(y_predicted-y_true)

        w1 = w1-rate*w1_derivative
        w2 = w2-rate*w2_derivative
        bias = bias-rate*bias_derivative

        print(f"epochs : {i}, w1 : {w1}, w2 : {w2}, bias : {bias}, loss : {loss}")

        if loss<=loss_threshold:
            break

    return w1, w2, bias

In [40]:
gradient_descent(X_train["age"], X_train["affordibility"], y_train, 1000, 0.4960)

epochs : 0, w1 : 0.9661065669301468, w2 : 0.9187460766241071, bias : -0.1460205689063377, loss : 0.7946601314454398
epochs : 1, w1 : 0.9398401385990321, w2 : 0.8501471584489816, bias : -0.27204171877303784, loss : 0.7406483743374357
epochs : 2, w1 : 0.9206706229599357, w2 : 0.7936519337479107, bias : -0.37956883651373846, loss : 0.7013993799659705
epochs : 3, w1 : 0.9078393941627181, w2 : 0.7481703672678416, bias : -0.47065669931226084, loss : 0.6736461369021787
epochs : 4, w1 : 0.9004883151964336, w2 : 0.7123266329840607, bias : -0.5475768037802378, loss : 0.6543742239079764
epochs : 5, w1 : 0.8977622397819759, w2 : 0.6846746837538349, bias : -0.6125610961688313, loss : 0.6411041158940357
epochs : 6, w1 : 0.898872736530929, w2 : 0.6638408579081043, bias : -0.667647813466844, loss : 0.6319542107371117
epochs : 7, w1 : 0.903128085649941, w2 : 0.6485980813362056, bias : -0.714612956066349, loss : 0.6255741155703062
epochs : 8, w1 : 0.9099405444741201, w2 : 0.637891884131865, bias : -0.7549579255824282, loss : 0.6210306466951737
epochs : 9, w1 : 0.9188209308829648, w2 : 0.6308382931078995, bias : -0.7899275779882415, loss : 0.6176949350236466
epochs : 10, w1 : 0.9293674654728488, w2 : 0.6267079932739048, bias : -0.8205413735279302, loss : 0.6151500779417477
epochs : 11, w1 : 0.9412529417905375, w2 : 0.6249054569185243, bias : -0.8476277051958028, loss : 0.6131225780329165
epochs : 12, w1 : 0.9542123124222752, w2 : 0.6249476737230809, bias : -0.8718564597914502, loss : 0.6114341856042202
epochs : 13, w1 : 0.9680316004667269, w2 : 0.6264446400558434, bias : -0.8937677612003234, loss : 0.609969180785688
epochs : 14, w1 : 0.9825384136156179, w2 : 0.6290824042086081, bias : -0.9137963664208237, loss : 0.6086525956830374
epochs : 15, w1 : 0.9975940301372732, w2 : 0.6326087779162735, bias : -0.9322919045379239, loss : 0.6074359015635548
epochs : 16, w1 : 1.013086895258436, w2 : 0.6368215134890808, bias : -0.9495354388985441, loss : 0.6062876762293682
epochs : 17, w1 : 1.028927325967657, w2 : 0.6415586306963057, bias : -0.9657529082888083, loss : 0.6051875483749874
epochs : 18, w1 : 1.0450432244684882, w2 : 0.646690558113404, bias : -0.9811259801463197, loss : 0.6041222799897449
epochs : 19, w1 : 1.0613766205686919, w2 : 0.6521137769838093, bias : -0.9958007872584079, loss : 0.6030832364414394
epochs : 20, w1 : 1.0778808889027722, w2 : 0.6577456948947829, bias : -1.0098949478407107, loss : 0.6020647543538376
epochs : 21, w1 : 1.0945185123386179, w2 : 0.6635205188022021, bias : -1.023503200311167, loss : 0.6010630892230995
epochs : 22, w1 : 1.1112592858481636, w2 : 0.6693859364296458, bias : -1.0367019235007624, loss : 0.600075736978464
epochs : 23, w1 : 1.1280788747899253, w2 : 0.6753004496673328, bias : -1.0495527617305407, loss : 0.5991009966004311
epochs : 24, w1 : 1.1449576579701564, w2 : 0.6812312328727917, bias : -1.0621055317212091, loss : 0.5981376880897596
epochs : 25, w1 : 1.1618797993398493, w2 : 0.6871524132517078, bias : -1.074400553635782, loss : 0.5971849705457896
epochs : 26, w1 : 1.1788325031633626, w2 : 0.6930436903839783, bias : -1.0864705204830256, loss : 0.596242224759844
epochs : 27, w1 : 1.1958054163763943, w2 : 0.6988892281276428, bias : -1.098341997485249, loss : 0.5953089773913082
epochs : 28, w1 : 1.212790149010671, w2 : 0.7046767652148543, bias : -1.1100366248326925, loss : 0.5943848519512359
epochs : 29, w1 : 1.229779889321078, w2 : 0.7103969014062836, bias : -1.1215720826600313, loss : 0.5934695370729175
epochs : 30, w1 : 1.2467690948758758, w2 : 0.7160425245656377, bias : -1.1329628653884156, loss : 0.5925627659336972
epochs : 31, w1 : 1.2637532445821105, w2 : 0.7216083508466148, bias : -1.1442209032090318, loss : 0.5916643028729974
epochs : 32, w1 : 1.2807286395952777, w2 : 0.7270905556723051, bias : -1.155356060980715, loss : 0.5907739346565746
epochs : 33, w1 : 1.2976922434494136, w2 : 0.7324864775934841, bias : -1.166376538804035, loss : 0.5898914647425598
epochs : 34, w1 : 1.314641553657684, w2 : 0.7377943806493152, bias : -1.1772891937200511, loss : 0.5890167094885249
epochs : 35, w1 : 1.331574498567944, w2 : 0.7430132636926099, bias : -1.1880997981252426, loss : 0.5881494956151285
epochs : 36, w1 : 1.3484893544878898, w2 : 0.7481427074196519, bias : -1.1988132474041109, loss : 0.5872896584845894
epochs : 37, w1 : 1.365384679080715, w2 : 0.7531827516723628, bias : -1.209433726804843, loss : 0.5864370409087463
epochs : 38, w1 : 1.3822592578229904, w2 : 0.758133797047179, bias : -1.2199648455989514, loss : 0.5855914923024703
epochs : 39, w1 : 1.3991120609506145, w2 : 0.7629965260218331, bias : -1.2304097449751197, loss : 0.584752868063345
epochs : 40, w1 : 1.4159422088272255, w2 : 0.7677718397555721, bias : -1.240771184842234, loss : 0.5839210291006053
epochs : 41, w1 : 1.4327489440773373, w2 : 0.7724608074761768, bias : -1.2510516136940708, loss : 0.5830958414634692
epochs : 42, w1 : 1.449531609153616, w2 : 0.777064625975358, bias : -1.2612532248681285, loss : 0.582277176036545
epochs : 43, w1 : 1.4662896282701743, w2 : 0.7815845872222635, bias : -1.2713780018734209, loss : 0.5814649082813089
epochs : 44, w1 : 1.483022492844332, w2 : 0.78602205249669, bias : -1.2814277549344892, loss : 0.5806589180099816
epochs : 45, w1 : 1.4997297497582467, w2 : 0.7903784317581574, bias : -1.2914041504756384, loss : 0.5798590891828519
epochs : 46, w1 : 1.516410991887424, w2 : 0.794655167219572, bias : -1.3013087349297843, loss : 0.579065309723164
epochs : 47, w1 : 1.5330658504519463, w2 : 0.7988537202969931, bias : -1.3111429539837518, loss : 0.5782774713456594
epochs : 48, w1 : 1.549693988833614, w2 : 0.8029755612698749, bias : -1.3209081681531134, loss : 0.5774954693961547
epochs : 49, w1 : 1.5662950975723349, w2 : 0.807022161116949, bias : -1.3306056654040512, loss : 0.5767192027003623
epochs : 50, w1 : 1.58286889031141, w2 : 0.8109949850979687, bias : -1.3402366713987477, loss : 0.5759485734207097
epochs : 51, w1 : 1.5994151005065882, w2 : 0.8148954877359356, bias : -1.3498023578276006, loss : 0.5751834869202626
epochs : 52, w1 : 1.6159334787500768, w2 : 0.8187251089222303, bias : -1.3593038492006497, loss : 0.5744238516330905
epochs : 53, w1 : 1.6324237905898795, w2 : 0.8224852709215549, bias : -1.3687422283975796, loss : 0.5736695789405685
epochs : 54, w1 : 1.6488858147482657, w2 : 0.8261773760973763, bias : -1.3781185412170027, loss : 0.5729205830532071
epochs : 55, w1 : 1.6653193416620076, w2 : 0.8298028052137465, bias : -1.387433800118601, loss : 0.5721767808976792
epochs : 56, w1 : 1.68172417228216, w2 : 0.8333629161976635, bias : -1.3966889873138353, loss : 0.5714380920087505
epochs : 57, w1 : 1.6981001170833179, w2 : 0.8368590432688697, bias : -1.4058850573304917, loss : 0.5707044384258664
epochs : 58, w1 : 1.7144469952420625, w2 : 0.8402924963622687, bias : -1.415022939151879, loss : 0.56997574459416
epochs : 59, w1 : 1.7307646339521758, w2 : 0.8436645607828347, bias : -1.4241035380118157, loss : 0.5692519372696775
epochs : 60, w1 : 1.7470528678505137, w2 : 0.8469764970447137, bias : -1.4331277369107438, loss : 0.5685329454286235
epochs : 61, w1 : 1.7633115385325173, w2 : 0.850229540855715, bias : -1.442096397905579, loss : 0.5678187001804422
epochs : 62, w1 : 1.7795404941404307, w2 : 0.8534249032160404, bias : -1.4510103632156905, loss : 0.5671091346845671
epochs : 63, w1 : 1.7957395890105794, w2 : 0.8565637706062441, bias : -1.4598704561791693, loss : 0.5664041840706728
epochs : 64, w1 : 1.8119086833687137, w2 : 0.8596473052443654, bias : -1.4686774820869288, loss : 0.5657037853622736
epochs : 65, w1 : 1.8280476430645474, w2 : 0.8626766453961502, bias : -1.4774322289168536, loss : 0.5650078774035264
epochs : 66, w1 : 1.8441563393383387, w2 : 0.865652905725483, bias : -1.486135467985924, loss : 0.5643164007890933
epochs : 67, w1 : 1.8602346486137407, w2 : 0.8685771776747211, bias : -1.494787954534798, loss : 0.5636292977969314
epochs : 68, w1 : 1.8762824523122572, w2 : 0.8714505298666948, bias : -1.5033904282565451, loss : 0.5629465123238843
epochs : 69, w1 : 1.8922996366855378, w2 : 0.8742740085218054, bias : -1.5119436137789972, loss : 0.5622679898239513
epochs : 70, w1 : 1.9082860926624632, w2 : 0.8770486378849883, bias : -1.5204482211083716, loss : 0.5615936772491179
epochs : 71, w1 : 1.9242417157085578, w2 : 0.8797754206583889, bias : -1.5289049460403756, loss : 0.560923522992641
epochs : 72, w1 : 1.9401664056957284, w2 : 0.8824553384364632, bias : -1.5373144705438242, loss : 0.5602574768346755
epochs : 73, w1 : 1.9560600667807109, w2 : 0.8850893521409129, bias : -1.5456774631208652, loss : 0.5595954898901475
epochs : 74, w1 : 1.9719226072909077, w2 : 0.8876784024534213, bias : -1.5539945791471386, loss : 0.5589375145587758
epochs : 75, w1 : 1.9877539396165447, w2 : 0.8902234102446078, bias : -1.5622664611945885, loss : 0.5582835044771463
epochs : 76, w1 : 2.0035539801082765, w2 : 0.8927252769979777, bias : -1.5704937393391452, loss : 0.5576334144727548
epochs : 77, w1 : 2.0193226489795264, w2 : 0.8951848852279333, bias : -1.5786770314550986, loss : 0.5569872005199327
epochs : 78, w1 : 2.035059870212977, w2 : 0.897603098891145, bias : -1.5868169434976573, loss : 0.5563448196975742
epochs : 79, w1 : 2.050765571470734, w2 : 0.899980763790763, bias : -1.5949140697749287, loss : 0.5557062301485898
epochs : 80, w1 : 2.0664396840077663, w2 : 0.9023187079731019, bias : -1.6029689932103415, loss : 0.5550713910410082
epochs : 81, w1 : 2.0820821425882996, w2 : 0.9046177421165466, bias : -1.610982285596364, loss : 0.5544402625306636
epochs : 82, w1 : 2.0976928854048893, w2 : 0.9068786599125209, bias : -1.6189545078402268, loss : 0.553812805725394
epochs : 83, w1 : 2.1132718539999473, w2 : 0.9091022384384371, bias : -1.6268862102022523, loss : 0.5531889826506917
epochs : 84, w1 : 2.128818993189534, w2 : 0.9112892385226004, bias : -1.6347779325272978, loss : 0.552568756216739
epochs : 85, w1 : 2.144334250989255, w2 : 0.9134404051010911, bias : -1.642630204469743, loss : 0.5519520901867763
epochs : 86, w1 : 2.159817578542126, w2 : 0.9155564675666826, bias : -1.650443545712399, loss : 0.5513389491467431
epochs : 87, w1 : 2.175268930048292, w2 : 0.9176381401098792, bias : -1.6582184661796546, loss : 0.550729298476138
epochs : 88, w1 : 2.190688262696495, w2 : 0.9196861220521834, bias : -1.6659554662451486, loss : 0.5501231043200483
epochs : 89, w1 : 2.206075536597209, w2 : 0.9217010981717144, bias : -1.6736550369342091, loss : 0.5495203335622973
epochs : 90, w1 : 2.221430714717364, w2 : 0.9236837390213151, bias : -1.681317660121287, loss : 0.5489209537996673
epochs : 91, w1 : 2.2367537628165897, w2 : 0.9256347012392895, bias : -1.688943808722576, loss : 0.5483249333171464
epochs : 92, w1 : 2.252044649384919, w2 : 0.9275546278529244, bias : -1.6965339468840017, loss : 0.5477322410641623
epochs : 93, w1 : 2.2673033455819005, w2 : 0.9294441485749466, bias : -1.70408853016474, loss : 0.5471428466317599
epochs : 94, w1 : 2.2825298251770674, w2 : 0.9313038800930737, bias : -1.7116080057164151, loss : 0.5465567202306815
epochs : 95, w1 : 2.2977240644917196, w2 : 0.9331344263528165, bias : -1.7190928124581173, loss : 0.5459738326703149
epochs : 96, w1 : 2.312886042341977, w2 : 0.9349363788336891, bias : -1.7265433812473656, loss : 0.5453941553384715
epochs : 97, w1 : 2.328015739983066, w2 : 0.9367103168189845, bias : -1.7339601350471383, loss : 0.5448176601819618
epochs : 98, w1 : 2.3431131410548067, w2 : 0.93845680765927, bias : -1.7413434890890849, loss : 0.5442443196879321
epochs : 99, w1 : 2.3581782315282593, w2 : 0.940176407029754, bias : -1.7486938510330257, loss : 0.5436741068659356
epochs : 100, w1 : 2.37321099965351, w2 : 0.9418696591816776, bias : -1.7560116211228411, loss : 0.5431069952307028
epochs : 101, w1 : 2.3882114359085547, w2 : 0.9435370971878749, bias : -1.7632971923388485, loss : 0.5425429587855857
epochs : 102, w1 : 2.40317953294926, w2 : 0.945179243182649, bias : -1.7705509505467592, loss : 0.5419819720066464
epochs : 103, w1 : 2.4181152855603743, w2 : 0.9467966085961048, bias : -1.7777732746433037, loss : 0.5414240098273657
epochs : 104, w1 : 2.4330186906075557, w2 : 0.9483896943830764, bias : -1.7849645366986135, loss : 0.5408690476239422
epochs : 105, w1 : 2.4478897469904024, w2 : 0.9499589912467843, bias : -1.7921251020954378, loss : 0.5403170612011631
epochs : 106, w1 : 2.462728455596454, w2 : 0.9515049798573548, bias : -1.799255329665279, loss : 0.5397680267788192
epochs : 107, w1 : 2.4775348192561437, w2 : 0.9530281310653299, bias : -1.80635557182152, loss : 0.5392219209786431
epochs : 108, w1 : 2.492308842698679, w2 : 0.954528906110292, bias : -1.8134261746896223, loss : 0.5386787208117498
epochs : 109, w1 : 2.5070505325088286, w2 : 0.9560077568247272, bias : -1.82046747823446, loss : 0.5381384036665599
epochs : 110, w1 : 2.5217598970845976, w2 : 0.9574651258332453, bias : -1.8274798163848678, loss : 0.5376009472971821
epochs : 111, w1 : 2.536436946595765, w2 : 0.9589014467472716, bias : -1.8344635171554626, loss : 0.537066329812244
epochs : 112, w1 : 2.551081692943272, w2 : 0.9603171443553244, bias : -1.8414189027658117, loss : 0.5365345296641418
epochs : 113, w1 : 2.565694149719434, w2 : 0.9617126348089873, bias : -1.8483462897570055, loss : 0.536005525638704
epochs : 114, w1 : 2.580274332168964, w2 : 0.9630883258046828, bias : -1.8552459891057005, loss : 0.5354792968452425
epochs : 115, w1 : 2.5948222571507884, w2 : 0.9644446167613526, bias : -1.8621183063356905, loss : 0.5349558227069837
epochs : 116, w1 : 2.6093379431006336, w2 : 0.965781898994143, bias : -1.868963541627067, loss : 0.5344350829518562
epochs : 117, w1 : 2.6238214099943726, w2 : 0.967100555884197, bias : -1.8757819899230228, loss : 0.5339170576036275
epochs : 118, w1 : 2.6382726793121103, w2 : 0.9684009630446464, bias : -1.8825739410343578, loss : 0.533401726973372
epochs : 119, w1 : 2.6526917740029945, w2 : 0.9696834884828983, bias : -1.8893396797417372, loss : 0.532889071651259
epochs : 120, w1 : 2.6670787184507363, w2 : 0.9709484927593062, bias : -1.8960794858957584, loss : 0.5323790724986457
epochs : 121, w1 : 2.681433538439823, w2 : 0.9721963291423141, bias : -1.9027936345148744, loss : 0.5318717106404652
epochs : 122, w1 : 2.695756261122412, w2 : 0.9734273437601598, bias : -1.909482395881226, loss : 0.5313669674578959
epochs : 123, w1 : 2.7100469149858863, w2 : 0.9746418757492198, bias : -1.9161460356344298, loss : 0.5308648245813029
epochs : 124, w1 : 2.724305529821065, w2 : 0.9758402573990784, bias : -1.9227848148633708, loss : 0.5303652638834397
epochs : 125, w1 : 2.738532136691046, w2 : 0.9770228142943995, bias : -1.9293989901960436, loss : 0.5298682674728986
epochs : 126, w1 : 2.7527267679006755, w2 : 0.978189865453678, bias : -1.9359888138874883, loss : 0.5293738176878021
epochs : 127, w1 : 2.7668894569666267, w2 : 0.9793417234649464, bias : -1.9425545339058659, loss : 0.5288818970897248
epochs : 128, w1 : 2.7810202385880767, w2 : 0.9804786946185082, bias : -1.949096394016713, loss : 0.5283924884578359
epochs : 129, w1 : 2.7951191486179665, w2 : 0.9816010790367713, bias : -1.95561463386542, loss : 0.5279055747832553
epochs : 130, w1 : 2.809186224034839, w2 : 0.9827091708012479, bias : -1.9621094890579716, loss : 0.5274211392636138
epochs : 131, w1 : 2.823221502915233, w2 : 0.9838032580767907, bias : -1.9685811912399906, loss : 0.5269391652978077
epochs : 132, w1 : 2.8372250244066306, w2 : 0.9848836232331295, bias : -1.9750299681741212, loss : 0.5264596364809445
epochs : 133, w1 : 2.8511968287009406, w2 : 0.9859505429637716, bias : -1.9814560438157915, loss : 0.5259825365994681
epochs : 134, w1 : 2.865136957008512, w2 : 0.9870042884023301, bias : -1.987859638387391, loss : 0.5255078496264587
epochs : 135, w1 : 2.8790454515326633, w2 : 0.9880451252363386, bias : -1.9942409684508984, loss : 0.5250355597170978
epochs : 136, w1 : 2.8929223554447154, w2 : 0.9890733138186121, bias : -2.0006002469789945, loss : 0.524565651204297
epochs : 137, w1 : 2.9067677128595255, w2 : 0.9900891092762116, bias : -2.0069376834246957, loss : 0.5240981085944787
epochs : 138, w1 : 2.9205815688115018, w2 : 0.9910927616170687, bias : -2.013253483789537, loss : 0.5236329165635061
epochs : 139, w1 : 2.9343639692310983, w2 : 0.9920845158343228, bias : -2.019547850690344, loss : 0.5231700599527549
epochs : 140, w1 : 2.948114960921774, w2 : 0.9930646120084266, bias : -2.0258209834246177, loss : 0.5227095237653225
epochs : 141, w1 : 2.9618345915374102, w2 : 0.9940332854070695, bias : -2.032073078034566, loss : 0.5222512931623703
epochs : 142, w1 : 2.9755229095601745, w2 : 0.9949907665829708, bias : -2.038304327369815, loss : 0.5217953534595878
epochs : 143, w1 : 2.9891799642788266, w2 : 0.9959372814695905, bias : -2.0445149211488234, loss : 0.5213416901237854
epochs : 144, w1 : 3.0028058057674514, w2 : 0.996873051474806, bias : -2.0507050460190337, loss : 0.5208902887695969
epochs : 145, w1 : 3.0164004848646164, w2 : 0.9977982935726021, bias : -2.0568748856157844, loss : 0.5204411351562998
epochs : 146, w1 : 3.0299640531529413, w2 : 0.9987132203928186, bias : -2.0630246206200127, loss : 0.5199942151847405
epochs : 147, w1 : 3.043496562939072, w2 : 0.9996180403090004, bias : -2.0691544288147736, loss : 0.5195495148943652
epochs : 148, w1 : 3.0569980672340544, w2 : 1.000512957524393, bias : -2.0752644851406, loss : 0.519107020460349
epochs : 149, w1 : 3.070468619734095, w2 : 1.0013981721561258, bias : -2.081354961749731, loss : 0.518666718190823
epochs : 150, w1 : 3.0839082748017064, w2 : 1.0022738803176245, bias : -2.087426028059234, loss : 0.5182285945241922
epochs : 151, w1 : 3.097317087447223, w2 : 1.003140274199291, bias : -2.0934778508030383, loss : 0.5177926360265424
epochs : 152, w1 : 3.1106951133106877, w2 : 1.003997542147492, bias : -2.099510594082914, loss : 0.517358829389134
epochs : 153, w1 : 3.1240424086440948, w2 : 1.0048458687418935, bias : -2.10552441941841, loss : 0.5169271614259762
epochs : 154, w1 : 3.13735903029399, w2 : 1.0056854348711772, bias : -2.111519485795778, loss : 0.5164976190714808
epochs : 155, w1 : 3.150645035684412, w2 : 1.006516417807177, bias : -2.1174959497159036, loss : 0.516070189378192
epochs : 156, w1 : 3.1639004828001753, w2 : 1.0073389912774688, bias : -2.123453965241266, loss : 0.5156448595145908
epochs : 157, w1 : 3.1771254301704874, w2 : 1.0081533255364505, bias : -2.129393684041947, loss : 0.5152216167629665
epochs : 158, w1 : 3.190319936852888, w2 : 1.0089595874349429, bias : -2.1353152554407093, loss : 0.5148004485173595
epochs : 159, w1 : 3.203484062417511, w2 : 1.0097579404883459, bias : -2.1412188264571657, loss : 0.5143813422815661
epochs : 160, w1 : 3.2166178669316614, w2 : 1.0105485449433835, bias : -2.1471045418510553, loss : 0.5139642856672094
epochs : 161, w1 : 3.2297214109446957, w2 : 1.0113315578434652, bias : -2.15297254416465, loss : 0.5135492663918664
epochs : 162, w1 : 3.242794755473208, w2 : 1.012107133092697, bias : -2.1588229737643063, loss : 0.5131362722772567
epochs : 163, w1 : 3.2558379619865097, w2 : 1.0128754215185705, bias : -2.1646559688811835, loss : 0.5127252912474856
epochs : 164, w1 : 3.268851092392401, w2 : 1.0136365709333603, bias : -2.1704716656511427, loss : 0.5123163113273398
epochs : 165, w1 : 3.2818342090232253, w2 : 1.0143907261942562, bias : -2.176270198153847, loss : 0.5119093206406384
epochs : 166, w1 : 3.2947873746222047, w2 : 1.015138029262259, bias : -2.1820516984510783, loss : 0.5115043074086291
epochs : 167, w1 : 3.3077106523300484, w2 : 1.0158786192598672, bias : -2.1878162966242884, loss : 0.5111012599484359
epochs : 168, w1 : 3.3206041056718294, w2 : 1.01661263252758, bias : -2.1935641208113985, loss : 0.5107001666715515
epochs : 169, w1 : 3.3334677985441266, w2 : 1.0173402026792426, bias : -2.1992952972428643, loss : 0.5103010160823752
epochs : 170, w1 : 3.346301795202423, w2 : 1.0180614606562592, bias : -2.2050099502770237, loss : 0.5099037967767908

(np.float64(3.8243792453432754),
 np.float64(1.0424089248140604),
 np.float64(-2.4161388502721217))

In [41]:
coef, intercept

(array([[3.7773602],
        [1.1495365]], dtype=float32),
 array([-2.5030148], dtype=float32))